### ISSUE TITLE
Crash. Imcompatibility with Laugicality(maybe). 

### ISSUE THREAD

**Issue by Umbraminf** [JavidPack/RecipeBrowser#32]
I try to enter a world, it loads until part of the 'rebuilding loot cache', then shuts down, and disble recipebrowser imediatly. 
Playing on windows 10 pro, 8GB RAM, 64bits. 

LOG FILE:
Index was outside the bounds of the array.
   at Laugicality.NPCs.EtherialGlobalNPC.ScaleExpertStats(NPC npc, Int32 numPlayers, Single bossLifeScale) na d:\Users\Alex\Documents\My Games\Terraria\ModLoader\Mod Sources\Laugicality\NPCs\EtherialGlobalNPC.cs:line 208
   at Terraria.ModLoader.NPCLoader.ScaleExpertStats(NPC npc, Int32 numPlayers, Single bossLifeScale)
   at Terraria.NPC.scaleStats()
   at Terraria.NPC.SetDefaults(Int32 Type, Single scaleOverride)
   at RecipeBrowser.LootCacheManager.Setup(Mod recipeBrowserMod)
   at RecipeBrowser.RecipeBrowser.PostAddRecipes()
   at Terraria.ModLoader.RecipeHooks.PostAddRecipes()

PRINT SCREEN:
![error recipes mod](https://user-images.githubusercontent.com/30694643/51938124-78aadf00-23f3-11e9-92ca-9880703b58ee.png)

**Comment by JavidPack** [comment]
That bug is in Laugicality, so I can't do anything about it.
